language: java
jdk:
  - openjdk11
notifications:
    slack:
      secure: "Gsjh1JDfTXJBBnvfMf//YgiSumWJ0eYKy0GwlXtxyoNVLfQ3i6vp+4vCZAcjWwD4sI9NDwesq68yG8gysk/4XFTLGaq58kS5B8jGNGPyziJOSWJieDRUJeguMzBvvvooRyQrlE9U5ob544kZglHJE6klBfaiaYDctGZph7CZxrgEMpa++fQvfZwwztM4OSGKhKnnzRPtewRCuBmxJju5u1bf/JqOK6JSVvXctgu81xXc96ww8roQztpKRrKWYEcCzdeen+EARUdGWXM0YCFLx/tChXqSndoKqjhDETDyWHtZlFLVHnHP8mO9wfPzbtXm2d5/CG9gZd6OTcPR+I1vQ8o7Bg2Tzhuwplj8PGBxN3HzMTnLtnZ+Lfh870YiZ+O6O3p2F+8YyB6Enq+5gxTdtH9GV0kXKLq9CVy+XFffp0ixj+X8WBaetdwTAyRwyeBmOMKRZ4YCuVwr4nJn3am+wappf9qmd1G3AFO00TEQZaiwPPVcaaC/Ex4oIK4wJXAF/qZLb2OKyPfLW/9w+u5BvpDU8J93MFe3CUbpoUlrZoKUudWLKgSI3G1fYMpMC0+cdKZlWgFwjzeAyeMV1CbH8M03nOW0XR4H4IDjW4z3Z9u3GqcFy7/JV4Nr++kN6LN0To836ZQvkD7Tb5HywjvE/Nzmre2z6moYxQubB0Tir4Q="
