language: java
jdk:
  - openjdk11
notifications:
    slack:
      secure: kXE09f07lw0xH7m8ANtYCf9kUsIKEW+RQKxyUkqyGU942663x2iF82QdvuAkEdyvaARYGXYHbGzW22YW3fuRK3nmq6mPRmSQTW5Ab0sdnhqccd7yQUcpxVo7ZICbRD/FPyxJTRmqZ1aNjBLObwczMuqZcvuPm9DM9v+SXb+zwDuGQfPnhHVXgLY7xv48skLPG5F9M2UIP3zx34Jofczmv87M7gsRWQJuEMSJ7YQh94MqqLeSA3pEeul0y3ySPlS9YOeDObxTqt35Rynf+Ik10mn0pA6/LBcfI7qJqal5p2TwFaqfOtKKK9/JLyEJcSZ6fPYYEiggm2lFwAaQn5dQAa784dXdy6aR8L+ixnod34vRuOhWJy/G+uOZnChqRhwFB5ZO0xqTm56fkzcbWsLQ5ysu64ChaqGAofkrXxRE0I3VTOVDz1w4wz0xtgN1WqXbSP1jtfzgIH8KWiFugNKWHScG2vjP6uR0xIwCQYHy0k7XryCaMoqNQecp+OzM/iSkdvjZnvRsQCiqcWaZGi9+h36b48rARbMrJACZebQ9AR8BW2kw6Am3Et98pb7WLr/3yY6Z+qdl0KySpaUQ2BHfo0noj3T+8gr57xZSvOiOebPbSl9TTERhoHHQmr6tolfwjIJSzSRzxJqpRlupqkEEgTJZh6g3ZDjLO01QgO6X/3M=
