#!/usr/bin/env bash

commit_msg=$(cat "${1:?Missing commit message file}")
#echo "Your commit message: $commit_msg"

num_char_ln1=`head -n 1 $1 | wc -c`

#checks if the first line's character count is greater than the threshold
if [ "$num_char_ln1" -gt "50" ]
then
    echo "Too big!"
    exit 1
fi

ln2=`head -n 2 $1 | tail -n 1`
#checks if the first character of line 2 is a new line
regex='^$'
if ! [[ $ln2 =~ $regex ]]; then
    echo "Second line should be a new line"
    exit 1
fi
