#!/usr/bin/env bash

commit_msg=$(cat "${1:?Missing commit message file}")
#echo "Your commit message: $commit_msg"

num_char_ln1=`head -n 1 $1 | wc -c`

#checks if the first line's character count is greater than the threshold
if [ "$num_char_ln1" -gt "60" ]
then
    echo "The first line of your commit message should have fewer than 60 characters!"
    exit 1
fi

ln2=`head -n 2 $1 | tail -n 1`

num_char_ln2=`echo "$ln2" | wc -c`

#checks if there is anything besides whitespace on the line
regex='^.*[^\r\n\t\f\c\ ].*$'

#makes sure that there aren't too many characters on the line
if [ "$num_char_ln2" -gt "3" ]
then
        echo "The second line of your commit message contains over three characters!"
        exit 1
elif [[ $ln2 =~ $regex ]]
then
        echo "The second line of your commit message must be a new line!"
        exit 1
fi

