#!/usr/bin/env bash

commit_msg=$(cat "${1:?Missing commit message file}")
#echo "Your commit message: $commit_msg"

num_char_ln1=`head -n 1 $1| wc -c`
num_lines=`cat $1 | wc -l`
line1=`head -n 1 $1`
line2=`head -n 2 $1`
default_merge_regex="$^(Merge branch '.+' ((into)|(for))).+$"

# if line 1 does not match the pattern of a default commit message
if [[ ! $line1 =~ $default_merge_regex ]];
then
        if [ "$num_char_ln1" -gt "50" ]; then
                echo 'Line 1 should be less than 50 characters'
                exit 1
        fi

        if [ "$num_lines" -eq "2" ]; then
                echo 'Should either be a one-line commit message, or a multiline message with a line 2 empty'
                exit 1
        elif [ "$num_lines" -gt "2" ]; then
                if [[ $line2 =~ ^.+$ ]]; then
                        echo 'Line 2 should be empty'
                        exit 1
                fi
        fi
fi
